name: Docker Build and Deploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:  # Allow manual trigger

env:
  IMAGE_NAME: ollama-gemma3n
  DOCKERFILE_PATH: deployment/docker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.timestamp.outputs.timestamp }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Update deployment script default image
        if: success()
        run: |
          echo "Docker image pushed successfully:"
          echo "  - ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          echo "  - ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.timestamp }}"
          echo ""
          echo "To use in RunPod:"
          echo "  python deployment/runpod/setup_runpod.py --docker-image ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"